# 
policy_path: "/home/melwu/unitree_mujoco/policy/29dof_lock_waist_no_hist/2025-11-26_14-25-59_5000.pt"
xml_path: "/home/melwu/unitree_mujoco/unitree_robots/g1/g1_29dof_lock_waist.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

kps: [100, 100, 100, 150, 40, 40, 
      100, 100, 100, 150, 40, 40,
      200,
      40,40,40,40,40,40,40,
      40,40,40,40,40,40,40]
kds: [2, 2, 2, 4, 2, 2, 
      2, 2, 2, 4, 2, 2,
      5,
      1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,]

default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
                  -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
                  0,
                  0.3, 0.25,0,0.97,0.15, 0,0,
                  0.3, -0.25,0,0.97,-0.15, 0,0]

ang_vel_scale: 0.2
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [1.0, 1.0, 1.0]
num_actions: 27
num_obs: 90 # 3+3+3 + 29*3 (+2=98)
history_length: 1

cmd_init: [0, 0.4, 0]

joint_names: ['left_hip_pitch_joint', 'right_hip_pitch_joint', 
            'waist_yaw_joint', 
            'left_hip_roll_joint', 'right_hip_roll_joint', 
            'left_hip_yaw_joint', 'right_hip_yaw_joint', 
            'left_knee_joint', 'right_knee_joint', 
            'left_shoulder_pitch_joint', 'right_shoulder_pitch_joint', 
            'left_ankle_pitch_joint', 'right_ankle_pitch_joint', 
            'left_shoulder_roll_joint', 'right_shoulder_roll_joint', 
            'left_ankle_roll_joint', 'right_ankle_roll_joint', 
            'left_shoulder_yaw_joint', 'right_shoulder_yaw_joint', 
            'left_elbow_joint', 'right_elbow_joint', 'left_wrist_roll_joint', 
            'right_wrist_roll_joint', 'left_wrist_pitch_joint', 
            'right_wrist_pitch_joint', 'left_wrist_yaw_joint', 
            'right_wrist_yaw_joint']
