# 
# policy_path: "humanoid/unitree_mujoco/policy/29dof_mimic_dance/policy.onnx"
policy_path: "humanoid/unitree_mujoco/policy/29dof_mimic_dance/2025-12-03_11-51-33.pt"
xml_path: "humanoid/unitree_mujoco/unitree_robots/g1/g1_29dof.xml"
motion_path: "humanoid/unitree_mujoco/simulate_python/motion_file/G1_Take_102.bvh_60hz.csv"

# Total simulation time
simulation_duration: 6000.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

kps: [40, 99, 40, 99, 28.5, 28.5, 
      40, 99, 40, 99, 28.5, 28.5,
      40,28.5,28.5,
      14.25,14.25,14.25,14.25,14.25,16.78,16.78,
      14.25,14.25,14.25,14.25,14.25,16.78,16.78]
kds: [2.55, 6.3, 2.55, 6.3, 1.81, 1.81, 
      2.55, 6.3, 2.55, 6.3, 1.81, 1.81,
      2.55,1.81,1.81,
      0.91,0.91,0.91,0.91,0.91,1.07,1.07,
      0.91,0.91,0.91,0.91,0.91,1.07,1.07,]
# kps: [100, 100, 100, 150, 40, 40, 
#       100, 100, 100, 150, 40, 40,
#       200,40,40,
#       40,40,40,40,40,40,40,
#       40,40,40,40,40,40,40]
# kds: [2, 2, 2, 4, 2, 2, 
#       2, 2, 2, 4, 2, 2,
#       5,5,5,
#       1,1,1,1,1,1,1,
#       1,1,1,1,1,1,1,]

default_angles: [-0.312,  0.0,  0.0,  0.669, -0.363, 0.0, 
                  -0.312,  0.0,  0.0,  0.669, -0.363, 0.0,
                  0,0,0,
                  0.2, 0.2,0,0.6,0, 0,0,
                  0.2, -0.2,0,0.6,0, 0,0]

ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 1.0
action_scale: [0.547, 0.351, 0.547, 0.351, 0.439, 0.439, 
               0.547, 0.351, 0.547, 0.351, 0.439, 0.439, 
               0.547, 0.439, 0.439,
               0.439, 0.439, 0.439, 0.439, 0.439, 0.0745, 0.0745, 
               0.439, 0.439, 0.439, 0.439, 0.439, 0.0745, 0.0745]

cmd_scale: 1.0
num_actions: 29
num_obs: 154 # = 29*2 + 6 + 3 + 29*3
history_length: 1

joint_names: ['left_hip_pitch_joint', 'right_hip_pitch_joint', 
            'waist_yaw_joint', 
            'left_hip_roll_joint', 'right_hip_roll_joint', 
            'waist_roll_joint', 
            'left_hip_yaw_joint', 'right_hip_yaw_joint', 
            'waist_pitch_joint', 
            'left_knee_joint', 'right_knee_joint', 
            'left_shoulder_pitch_joint', 'right_shoulder_pitch_joint', 
            'left_ankle_pitch_joint', 'right_ankle_pitch_joint', 
            'left_shoulder_roll_joint', 'right_shoulder_roll_joint', 
            'left_ankle_roll_joint', 'right_ankle_roll_joint', 
            'left_shoulder_yaw_joint', 'right_shoulder_yaw_joint', 
            'left_elbow_joint', 'right_elbow_joint', 
            'left_wrist_roll_joint', 'right_wrist_roll_joint', 
            'left_wrist_pitch_joint', 'right_wrist_pitch_joint', 
            'left_wrist_yaw_joint', 'right_wrist_yaw_joint']